
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network
    volumes:
      - ./zookeeper_data:/var/lib/zookeeper

  gps-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://gps-kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    volumes:
      - ./kafka_data:/var/lib/kafka/data
    user: "0"

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    restart: always
    ports:
      - "28080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "gps-kafka:29092"
    depends_on:
      - gps-kafka
    networks:
      - kafka-network

  gps-streaming:
    image: lmao1415/fish-kafka-gps-python
    ports:
      - "8010:8010"
    environment:
      kafka_host: gps-kafka:29092
      server_port: 8010
    depends_on:
      - gps-kafka
    networks:
      - kafka-network

networks:
  kafka-network:
